### ISSUE TITLE
Having doubt regarding the Rawdata in code :final_results_gender_test.ipynb

### ISSUE THREAD

**Issue by vikash512** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#1]
having doubt regarding these lines, what is the data in that and which format .

mylist= os.listdir('RawData/')

data, sampling_rate = librosa.load('RawData/f11 (2).wav')

**Comment by MITESHPUTHRANNEU** [comment]
Hello vikash512,

The data is audio files in .wav format. The data source has been linked in the readme file.
In the second line the librosa library helps to extract data from the audio files, which is stored in as time in second and its sampling rate.

**Comment by Arunpoochelvan** [comment]
Hi,  Can you please share us the RawData/ file? as we don't see 1800 audio files when combining both the dataset you mentioned on readme

**Comment by vlkare** [comment]
Yes please do share the file

**Comment by ejlok1** [comment]
The raw SAVEE dataset is seperated into 4 folders namely DC, JE, KJ, KL. What Mitesh has done here is combine them all into a single folder. Because there's a clash in the naming of the files, The audio file f10.wav for instance exist in all 4 folders. hence why the file when combine goes f10 (2).wav

**Comment by vlkare** [comment]
Means I have to combine all the files from the 4 folder into one??
And where is RAVDESS data used??

**Comment by vlkare** [comment]
RAVDESS data and SAVEE data has to combine in a same file.??? Thats is what
it is in RawData/???

**Comment by ejlok1** [comment]
Yes correct they are all in the same folder. The for loop iterates through various if statements. It first goes through the RAVDESS file format first, then SAVEE as the last bunch.
