### ISSUE TITLE
Contribution for an example

### ISSUE THREAD

**Issue by s3afroze** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#11]
Hey, 
Since there is no contact info on your profile. I wanted to share a project we built at a hackathon last month using your model. 
Thank you very much for uploading the source code. It was a huge help!

Best,

Shahzeb

**Comment by MITESHPUTHRANNEU** [comment]
Hey @s3afroze that's really good to hear. I would really like to know more about your project. You can attach a link here or connect with me on [LinkedIn](https://www.linkedin.com/in/miteshputhran/)

**Comment by s3afroze** [comment]
I am sorry for missing the comment. I have sent you a request on LinkedIn. 
Here is a video of the working product:
[video_link](https://www.youtube.com/watch?v=1EfA26LsY18)
Again thank you for writing back : )

**Comment by MITESHPUTHRANNEU** [comment]
Great..!!!
