### ISSUE TITLE
permission error 13

### ISSUE THREAD

**Issue by dangvansam98** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#13]
i cant run code
error:
C:\Speech-Emotion-Analyzer>python train.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 102, in <module>
    X,sample_rate = librosa.load('data/'+y)
  File "C:\Python35\lib\site-packages\librosa\core\audio.py", line 112, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "C:\Python35\lib\site-packages\audioread\__init__.py", line 80, in audio_open
    return rawread.RawAudioFile(path)
  File "C:\Python35\lib\site-packages\audioread\rawread.py", line 61, in __init__
    self._fh = open(filename, 'rb')
PermissionError: [Errno 13] Permission denied: 'C:\\Speech-Emotion-Analyzer\\data\\Actor_01'

**Comment by MITESHPUTHRANNEU** [comment]
You need to give it administrator access as you are directly accessing it from C:\
Try creating a folder in your desktop of any other place and run your project.

**Comment by dangvansam98** [comment]
i fixed it :)) but train in SAVEE database but get acc <0.5 how to improve acc
and cant test by other file script python i not use jupyter notebook. thanks

**Comment by MITESHPUTHRANNEU** [comment]
Try getting more data from other sources. That should help.

**Comment by kudakwashez** [comment]
> i fixed it :)) but train in SAVEE database but get acc <0.5 how to improve acc
> and cant test by other file script python i not use jupyter notebook. thanks

How did you fix the pemmission problem?

**Comment by dangvansam98** [comment]
You should move project to another partition .not Windows “C:” partition

**Comment by Daydreamer05** [comment]
I'm getting permission denied error even after moving boh rpoject  and dataset to another drive.


> You should move project to another partition .not Windows “C:” partition
I have moved both project and data to another drive.But still i'm getting permission error
