### ISSUE TITLE
Dataset question

### ISSUE THREAD

**Issue by hackiey** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#14]
Hi, thanks for the work, I have a question about the samples number. After I filter out all the data (ravdess and savee), I just have 1200 samples, 960 train data, and the final acc is around 0.5. I found your train samples is 1378 (X_train.shape is 1378*216), I wonder what I did wrong.

**Comment by MITESHPUTHRANNEU** [comment]
Hi @hackiey, it's just the number of files that I had in the dataset. They must have changed the number of audio files in their website.

**Comment by hackiey** [comment]
Hi, I calculated the number of the dataset, in the RAVDESS, there are 96 samples of neutral, and 192 samples in each of the other categories, a total of 1500 samples, I got 192*5 = 960 samples from this dataset. in the SAVEE, there are 60 samples per category, a total of 480 samples, I got 60*4=240 samples from this dataset.
Because there are about 2,000 samples in total, the number of our data sets should be the same.

**Comment by MITESHPUTHRANNEU** [comment]
I am having around 2880 files in my dataset.

**Comment by hackiey** [comment]
wow, maybe they change the dataset, how can I get this data? or could you upload this data?

**Comment by Arunpoochelvan** [comment]
Can you upload the dataset?

**Comment by Glastond** [comment]
Yeah please... because it's creating a lot of confusion for me... Uploading the database will help me a lot! By the way great work!

**Comment by Arunpoochelvan** [comment]
> Yeah please... because it's creating a lot of confusion for me... Uploading the database will help me a lot! By the way great work!

I got it brother, Ref this link you got all the dataset https://github.com/preranas20/Emotion-Detection-in-Speech/tree/master/Emotion%20Detection%20in%20Speech           ROCK AND ROLL

**Comment by Arunpoochelvan** [comment]
> wow, maybe they change the dataset, how can I get this data? or could you upload this data?

I got it brother, Ref this link you got all the dataset https://github.com/preranas20/Emotion-Detection-in-Speech/tree/master/Emotion%20Detection%20in%20Speech ROCK AND ROLL

**Comment by drbln** [comment]
> Hi, I calculated the number of the dataset, in the RAVDESS, there are 96 samples of neutral, and 192 samples in each of the other categories, a total of 1500 samples, I got 192 x 5 = 960 samples from this dataset. in the SAVEE, there are 60 samples per category, a total of 480 samples, I got 60 x 4=240 samples from this dataset.
> Because there are about 2,000 samples in total, the number of our data sets should be the same.

Hi, did you solve this problem? I still don't understand what data should be added to improve the accuracy of work.
