### ISSUE TITLE
How to increase accuracy?

### ISSUE THREAD

**Issue by uneverknwwhoim** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#17]
I am getting very less accuracy. 
I have a dataset of 1700+ audio wav files.
please tell me how to increase the accuracy because i m getting only 8.5% accuracy after traning.
help me please. as i m a beginner

**Comment by MITESHPUTHRANNEU** [comment]
Hello Syed Shah,
Try to start training with the model parameters that I have used. After that you can change the parameters and experiment.
