### ISSUE TITLE
Regarding the dataset

### ISSUE THREAD

**Issue by Glastond** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#18]
I really liked your work ... But I am very confused how you combined the two datasets.. Can you plz share the whole dataset as it will save a lot of my time and it will be easier for me to figure out things as I am a beginner..Thanks a lot! :)

**Comment by MITESHPUTHRANNEU** [comment]
Hello @Glastond . I just combined the files from two sources and put them in one folder. While parsing through the files during processing, just mention the file names that you want to process. You can see it in my notebook cell 11.
Unfortunately I don't have the dataset in my system anymore to upload.

**Comment by Arunpoochelvan** [comment]
> Hello @Glastond . I just combined the files from two sources and put them in one folder. While parsing through the files during processing, just mention the file names that you want to process. You can see it in my notebook cell 11.
> Unfortunately I don't have the dataset in my system anymore to upload.

I got it brother, Ref this link you got all the dataset https://github.com/preranas20/Emotion-Detection-in-Speech/tree/master/Emotion%20Detection%20in%20Speech ROCK AND ROLL

**Comment by Glastond** [comment]
thanks buddy

**Comment by Nikhilbharu08** [comment]
> > Hello @Glastond . I just combined the files from two sources and put them in one folder. While parsing through the files during processing, just mention the file names that you want to process. You can see it in my notebook cell 11.
> > Unfortunately I don't have the dataset in my system anymore to upload.
> 
> I got it brother, Ref this link you got all the dataset https://github.com/preranas20/Emotion-Detection-in-Speech/tree/master/Emotion%20Detection%20in%20Speech ROCK AND ROLL

Great work!! But please do grant permission for download!!
