### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by uneverknwwhoim** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#19]
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder

X_train = np.array(trainfeatures)
y_train = np.array(trainlabel)
X_test = np.array(testfeatures)
y_test = np.array(testlabel)

lb = LabelEncoder()

y_train = np_utils.to_categorical(lb.fit_transform(y_train))
y_test = np_utils.to_categorical(lb.fit_transform(y_test))

ERROR AT THIS LINE... please help

**Comment by uneverknwwhoim** [comment]
can anyone help me on this?? please

**Comment by MITESHPUTHRANNEU** [comment]
@uneverknwwhoim can you post the error you encounter and at which specific line are you getting it?

**Comment by uneverknwwhoim** [comment]
![image](https://user-images.githubusercontent.com/32920949/54758182-b406a480-4c11-11e9-84df-42ae6a21ea78.png)

**Comment by uneverknwwhoim** [comment]
![image](https://user-images.githubusercontent.com/32920949/54758224-c680de00-4c11-11e9-8b5a-6f89e3af7728.png)

**Comment by uneverknwwhoim** [comment]
checkout the screenshot.. 
and pls help.. thank u in advance

**Comment by MITESHPUTHRANNEU** [comment]
print your (y_train) and (y_test) and see if the labels are all in the array.

**Comment by uneverknwwhoim** [comment]
![image](https://user-images.githubusercontent.com/32920949/54761516-3db97080-4c18-11e9-8445-773efc804be1.png)
it is listing out as follows

**Comment by MITESHPUTHRANNEU** [comment]
There are issues with your labels in (y_test). You can see that there are integers like 0 which shouldn't exist.

**Comment by uneverknwwhoim** [comment]
How do i clear that anyidea? I didnt do anything i just loaded my audio data set and ran your project..
Please help me as i am a beginner.. i would be very thankful to u:)

**Comment by MITESHPUTHRANNEU** [comment]
There might be either of two issues here. Either those labels have been converted to zero or those zeros are extra. Check this by checking the shape of the training and test dataset.
Print shape(X_train), shape(y_train), shape(x_test) and shape(y_test).  train and test shapes should match.

**Comment by Nandy-Saran** [comment]
Hi Mithesh! I am also getting the same error as uneverknwwhoim. I checked the dataset, it has 1851 files which is a combination of RAVDESS and SAVEE. While dividing data into testing and training sets, the size of the testing and training sets differ. Also X_train and y_train doesn't have the same shape.

I am getting NaN values which are then replaced by 0 after this code : rnewdf=rnewdf.fillna(0).
Please do provide some assistance as soon as possible

**Comment by Nandy-Saran** [comment]
I will share you my folder of the audio files if needed.

**Comment by MITESHPUTHRANNEU** [comment]
@Nandy-Saran  You won't have same shape for X_train and y_train. They should have same number of rows but features will differ. It doesn't really matter how many number of files you have before splitting.

**Comment by uneverknwwhoim** [comment]
@Nandy-Saran did u solve the problem ??

**Comment by uneverknwwhoim** [comment]
@MITESHPUTHRANNEU 
rows are same though and features different when i checked.. but still the same error..
please help...
![image](https://user-images.githubusercontent.com/32920949/55257261-544d7080-5285-11e9-9857-b3f0023bff81.png)

**Comment by uneverknwwhoim** [comment]
@MITESHPUTHRANNEU i even tried to delete the NaN values using dropna() but then i am getting y_train and X_train features different..

**Comment by uneverknwwhoim** [comment]
@MITESHPUTHRANNEU i would be very glad if u help me out of this asap..

**Comment by MITESHPUTHRANNEU** [comment]
@uneverknwwhoim The problem is as you stated. If you don't remove the null values, then you would be getting the error you stated at the top. If you remove the null values then the shape of X_train and y_train don't match.  So ultimately the problem is 'y'. For some reason there are null labels in your dataset. You have make sure to fix that, then everything would be fine.

**Comment by uneverknwwhoim** [comment]
Can i get a dataset link of yours?

**Comment by MITESHPUTHRANNEU** [comment]
@uneverknwwhoim I have linked the datasets in the readme file and those are only ones which I used for this project.

**Comment by uneverknwwhoim** [comment]
I am getting an accuracy of 0.0806 % 

I have included 2k+ audio files still am not getting the accuracy of 70-80%?
What to do?

**Comment by MITESHPUTHRANNEU** [comment]
@uneverknwwhoim  try augmenting the data and using different sampling rate to extract more features per audio file.

**Comment by Nikhilbharu08** [comment]
> Hi Mithesh! I am also getting the same error as uneverknwwhoim. I checked the dataset, it has 1851 files which is a combination of RAVDESS and SAVEE. While dividing data into testing and training sets, the size of the testing and training sets differ. Also X_train and y_train doesn't have the same shape.
> 
> I am getting NaN values which are then replaced by 0 after this code : rnewdf=rnewdf.fillna(0).
> Please do provide some assistance as soon as possible

Hi
Can you please share me the datasets!! I'm not able get those numbers!!

**Comment by Nikhilbharu08** [comment]
> I am getting an accuracy of 0.0806 %
> 
> I have included 2k+ audio files still am not getting the accuracy of 70-80%?
> What to do?

Hi
Can you provide me the datasets !!
