### ISSUE TITLE
how to run this code in flask server

### ISSUE THREAD

**Issue by Nikhilbharu08** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#23]
Hi
How do i run your code in flask server,

**Comment by MITESHPUTHRANNEU** [comment]
@Nikhilbharu08, you can used the trained model directly or use your own model. 

Just create your server code and front end which you can find easy tutorials online. Include your trained model location and supply it your input. Care should be taken are regarding the audio clippings with the desired sampling rate. If they don't match the model wouldn't make any predictions.

**Comment by Nikhilbharu08** [comment]
> @Nikhilbharu08, you can used the trained model directly or use your own model.
> 
> Just create your server code and front end which you can find easy tutorials online. Include your trained model location and supply it your input. Care should be taken are regarding the audio clippings with the desired sampling rate. If they don't match the model wouldn't make any predictions.

yeah i have created a front end to choose a audio file of .wav format file,  
can you please give more details/info regarding the sampling rate which you mentioned !!!?

**Comment by MITESHPUTHRANNEU** [comment]
Hey @Nikhilbharu08, sampling rate is what you change according to the number of features you want to extract from the audio files. Higher sampling rates means more features.
