### ISSUE TITLE
Issue in scoring on different .wav sound files

### ISSUE THREAD

**Issue by yashkumar94** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#24]
Whenever i am scoring the model on different set of .wav sound, during extracting the features with same parameters I am getting different number of features. How to overcome this problem?

**Comment by MITESHPUTHRANNEU** [comment]
The reason is you are just relying on the parameters form the code file. The audio that you provide should be clipped to 4 sec. You can find more parameters in the audio recorder notebook file. 

Following that you can find same number of features after it's extracted.
