### ISSUE TITLE
Reagarding the labelling

### ISSUE THREAD

**Issue by aningo123** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#25]
Can you help me in the code how you have set the labels. I am unable to detect the female emotion.

**Comment by MITESHPUTHRANNEU** [comment]
Hello @aningo123 the labels are set based on the audio file names. The dataset website has provided the details on the creating the labels for individual audio files. 

(For example, if the audio file name ends with 04 then those files belong to female actor who is portraying a sad emotion.)
