### ISSUE TITLE
how do I use audios larger than 4 seconds?

### ISSUE THREAD

**Issue by marvinpx42** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#26]

**Comment by MITESHPUTHRANNEU** [comment]
Hey @marvinpx42 , are you talking about the training process or using the trained model on a audio file?

**Comment by marvinpx42** [comment]
thanks for replying, from the trained model.

**Comment by MITESHPUTHRANNEU** [comment]
The trained model can't take more than 4 seconds as an input. It takes exactly 216 features as an input due to the sampling rate specified during training. You would have to train your own model using higher sampling rate. Hope this helps.
