### ISSUE TITLE
对中文的识别效果怎么样

### ISSUE THREAD

**Issue by lzj520** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#30]

**Comment by MITESHPUTHRANNEU** [comment]
Sorry, I don't understand the language. Can you post it in English.

**Comment by MITESHPUTHRANNEU** [comment]
[https://github.com/MITESHPUTHRANNEU/Speech-Emotion-Analyzer/issues/31](url)

**Comment by lzj520** [comment]
What is the recognition effect of Chinese

**Comment by lzj520** [comment]
![image](https://user-images.githubusercontent.com/28917075/61357880-b7522a00-a8ab-11e9-8cfb-d7a8b11c889b.png)
whether it is normal or not

**Comment by MITESHPUTHRANNEU** [comment]
This is not normal. The difference between your training and validation error is increasing as you train your model. This means that your model is overfitting and would not be able to recognize or predict the emotions on the audio files it has never encountered before

**Comment by lzj520** [comment]
------------------ 原始邮件 ------------------
发件人: "Mitesh Puthran"<notifications@github.com>;
发送时间: 2019年7月17日(星期三) 晚上8:22
收件人: "MITESHPUTHRANNEU/Speech-Emotion-Analyzer"<Speech-Emotion-Analyzer@noreply.github.com>;
抄送: "$天授*"<527263822@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [MITESHPUTHRANNEU/Speech-Emotion-Analyzer] 对中文的识别效果怎么样 (#30)




This is not normal. The difference between your training and validation error is increasing as you train your model. This means that your model is overfitting and would not be able to recognize or predict the emotions on the audio files it has never encountered before

**Comment by lzj520** [comment]
I trained the 16000 sample rate audio, Chinese corpus removal,duration=2.5,offset=0.5, and obtained the results. If the length of the audio is uncertain, how can I accurately obtain the accuracy of the model? If duration=2.5,offset=0.5, ValueError: Error when checking input may occur:Expected conv1d_1_input to have shape (32, 1) but got array with shape (24, 1)

**Comment by MITESHPUTHRANNEU** [comment]
You can try to increase the sampling rate to anything greater than 16000. This way you can extract more number of features from the audio files. As you have clipped your audio files to 2.5 sec, try increasing it to maybe 3 sec or less than 2.5 as you described some files might be smaller. If some of the audio files are smaller then the features would be 0 for that particular audio file.

The ValueError that you are facing is due to some dimension error in your input data. Check the dimension of the test and training data.

**Comment by lzj520** [comment]
I tried duration=1,sr=22050*2, and recognized emotions as anger and happiness. The recognition effect was poor, so how to improve?

**Comment by MITESHPUTHRANNEU** [comment]
duration = 1 is not a good option. If you are just providing it 1 sec of audio, it is difficult to extract valuable features. I would suggest you to have atleast 2-3 seconds. This way the model has features where it can distinguish between different emotions.

**Comment by lzj520** [comment]
How to train the corpus not enough 2 seconds will make mistakes

**Comment by MITESHPUTHRANNEU** [comment]
Are you saying that the corpus you have consist of audio files less than 2 secs long?

**Comment by lzj520** [comment]
Yes, I use Chinese corpus, which contains audio files that are not 2 seconds slow. The training result is not ideal
![image](https://user-images.githubusercontent.com/28917075/61756724-06d6af80-adf0-11e9-86a2-cd26615f2d31.png)

**Comment by lzj520** [comment]
Duration =2, ValueError: Error when checking input: expected conv1d_1_input to have shape (173, 1) but got array with shape (155, 1)
Is there any way to adjust it

**Comment by lzj520** [comment]
I tried to modify the parameters and got both emotions right 73 percent of the time, but always got the following results when using the audio test
![image](https://user-images.githubusercontent.com/28917075/61760879-85871900-adff-11e9-9fed-90d87363427e.png)

**Comment by lzj520** [comment]
按照您的代码训练结果如下
![image](https://user-images.githubusercontent.com/28917075/61773601-a3687400-ae27-11e9-9cc2-3fc5c5f58218.png)

**Comment by lzj520** [comment]
Do not modify your code training results as follows
![image](https://user-images.githubusercontent.com/28917075/61773691-e3c7f200-ae27-11e9-9b9e-c2c4d304616c.png)

**Comment by MITESHPUTHRANNEU** [comment]
Yeah, the shape of the input is different than what you are passing it in conv_1d layer. Refer to cell number 30 and 45, there you can see that I checked the shape of my training set and then supplied the same shape as input to the conv_1d layer in the 45th cell.

When you are testing it out on the live predictions, the audio file you passed as the input doesn't have too many features after extraction and its just giving two features. One starting with 1 and other with 0.
