### ISSUE TITLE
Does your model work regardless the language?

### ISSUE THREAD

**Issue by hzitoun** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#31]
I want to do the same but with french voices, what should I change?

Thanks in advance.

**Comment by MITESHPUTHRANNEU** [comment]
It depends on lot of factors to be honest. Emotions are portrayed in a similar fashion. For example, if a person is angry there is a high probability that the person would be talking in a high voice, which in turn means higher amplitude in the audio recording and the model should detect the emotions. 

Try for yourself and do let me know how it works on French.
