### ISSUE TITLE
Can't open file with.

### ISSUE THREAD

**Issue by LavenderMP** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#32]
Currently I am trying to re-procedure processes in your final_results_gender_test notebook but I ran into an issue which is can not load file from RAVDESS
Here is my error:

> ---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)
<ipython-input-22-17182666fe53> in <module>
      5 
      6 
----> 7 sr,x = scipy.io.wavfile.read(wav_file)
      8 
      9 ## Parameters: 10ms step, 30ms window

~/tmp/deepspeech-venv/lib/python3.7/site-packages/scipy/io/wavfile.py in read(filename, mmap)
    246                 raise ValueError("Unexpected end of file.")
    247             elif len(chunk_id) < 4:
--> 248                 raise ValueError("Incomplete wav chunk.")
    249 
    250             if chunk_id == b'fmt ':

ValueError: Incomplete wav chunk.

**Comment by WestbrookZero** [comment]
@LavenderMP  How did you solve it?
