### ISSUE TITLE
Where is rawdata file????

### ISSUE THREAD

**Issue by jholar** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#35]
If you guys are posting codes then make sure that everything is working correctly otherwise dont post such stuff. 
You are wasting times of coders who are genuinely taking interest in speech analysis.
Please recheck all files and update them asap.

Thank you

**Comment by SiemenDerycke** [comment]
The links to the data are in the README...

**Comment by deeptech18** [comment]
> The links to the data are in the README...

what you used i m using data from given link but getting error
