### ISSUE TITLE
my val_accuracy only has 40+%

### ISSUE THREAD

**Issue by bigcash** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#40]
i use the data, two of the RAVDESS and SAVEE. not 2000, but 1920。
i try to train a new model, but only got "942/942 [==============================] - 1s 2ms/step - loss: 0.2656 - accuracy: 0.9013 - val_loss: 1.9338 - val_accuracy: 0.4341"
you can see that my train data has 942 item, not 1378. that's the problem.

**Comment by MITESHPUTHRANNEU** [comment]
Try augmenting the data by adding more data files from different sources. It will improve the accuracy.
