### ISSUE TITLE
ValueError: Shapes (None, 4) and (None, 10) are incompatible

### ISSUE THREAD

**Issue by Arafat4341** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#52]
In the model training part, line:
`cnnhistory=model.fit(x_traincnn, y_train, batch_size=16, epochs=700, validation_data=(x_testcnn, y_test))`

I am getting the following error:
`ValueError: Shapes (None, 4) and (None, 10) are incompatible`

Would anyone kindly tell me why am I getting this and how to solve this?
Thanks in advance!

**Comment by Arafat4341** [comment]
Sorry I found the problem and fixed it.

**Comment by SpooderManEXE** [comment]
how did you solve it?
