### ISSUE TITLE
Need A help...

### ISSUE THREAD

**Issue by uneverknwwhoim** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#8]
Hi, i am a beginner ... Can you help me with where to add the path of my dataset in the code? 
and it would be very helpful for me if you help me how to run the project..! i would be very thankful to you..
#request.

**Comment by maomaolan** [comment]
good work, and thank you a lot

**Comment by MITESHPUTHRANNEU** [comment]
@uneverknwwhoim I have done it on cell number 4. 
The 'RawData' is the path to the folder which contains all the audio files.
