### ISSUE TITLE
I just want to use the saved .h5 model to test my own inputs.

### ISSUE THREAD

**Issue by uneverknwwhoim** [MITESHPUTHRANNEU/Speech-Emotion-Analyzer#9]
Would you mind telling me how the input should be given to the models and how the outputs would be recieved

**Comment by MITESHPUTHRANNEU** [comment]
Hello @uneverknwwhoim ,
You can have a look at loading the model step in the jupyter notebook.

**Comment by Arunpoochelvan** [comment]
When i do try to load the pretrained model it says 8 % Accuracy

**Comment by Nikhilbharu08** [comment]
> When i do try to load the pretrained model it says 8 % Accuracy

hi Arun
Did you get an accuracy ....??of around 70%
